/*** Generated by streamline 0.4.11 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb; (function() {






  var Author, Post, factory_render_page, render_post, _;

  _ = require("underscore");

  Post = require("../models/post").Post;

  Author = require("../models/author").Author;

  exports.index = function(req, res) {
    return res.render("index", {
      title: "Express" }); };



  render_post = function(_arg) {
    var p;
    p = _arg.p;
    return p; };


  factory_render_page = function(_arg) {
    var page, render_name;
    page = _arg.page, render_name = _arg.render_name;
    return function(req, res, next) {
      return page(req, res, function(err, view_info) {
        console.log(err);
        if (err) {
          next(err);
          return; } ;

        return res.render("index", view_info); }); }; };




  exports.factory_show_posts = function(_arg) {
    var page;
    _arg;
    page = function page__1(req, res, __) { var lpost, status; var __frame = { name: "page__1", line: 46 }; return __func(__, this, arguments, page__1, 2, __frame, function __$page__1() {

        status = { };
        return Post.find({ }).populate("author").exec(__cb(__, __frame, 3, 14, function ___(__0, __1) { lpost = __1;
          console.log(lpost);
          lpost = _.map(lpost, function(p) {
            return render_post({
              p: p }); });


          console.log(lpost);
          return __(null, {
            title: "Pippo",
            lpost: lpost,
            status: status }); }, true)); }); };


    return factory_render_page({
      page: page,
      render_name: "index" }); };



}).call(this);