// Generated by CoffeeScript 1.8.0

/*
streamline.options = { "callback": "__" };
 */

(function() {
  var _;

  _ = require("underscore");

  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Express'
    });
  };

}).call(this);
