// Generated by CoffeeScript 1.6.3
/*
streamline.options = { "callback": "__" };
*/


(function() {
  var Author, Post, factory_render_page, render_post, _;

  _ = require("underscore");

  Post = require("../models/post").Post;

  Author = require("../models/author").Author;

  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Express'
    });
  };

  render_post = function(_arg) {
    var p;
    p = _arg.p;
    return p;
  };

  factory_render_page = function(_arg) {
    var page, render_name;
    page = _arg.page, render_name = _arg.render_name;
    return function(req, res, next) {
      return page(req, res, function(err, view_info) {
        console.log(err);
        if (err) {
          next(err);
          return;
        }
        return res.render('index', view_info);
      });
    };
  };

  exports.factory_show_posts = function(_arg) {
    var page;
    _arg;
    page = function(req, res, __) {
      var lpost, status;
      status = {};
      lpost = Post.find({}).populate("author").exec(__);
      console.log(lpost);
      lpost = _.map(lpost, function(p) {
        return render_post({
          p: p
        });
      });
      console.log(lpost);
      return {
        title: "Pippo",
        lpost: lpost,
        status: status
      };
    };
    return factory_render_page({
      page: page,
      render_name: "index"
    });
  };

}).call(this);
