// Generated by CoffeeScript 1.6.3
/*
streamline.options = { "callback": "__" };
*/


(function() {
  var cascade_delete, sync;

  sync = require('../sync');

  exports.cascade_delete = cascade_delete = function(_arg) {
    var Model, done, query;
    Model = _arg.Model, query = _arg.query, done = _arg.done;
    return Model.find(query, function(err, lobj) {
      if (err) {
        done(err);
        return;
      }
      return sync.serialize_each(lobj, function(n, obj) {
        return obj.remove(n);
      }, function(err) {
        if (err) {
          return done(err);
        } else {
          return done();
        }
      });
    });
  };

}).call(this);
